In [1]:
import numpy as np

In [2]:
first_array  = np.array([1,2,3,4,5,6,1,2,32,5,7,8])
print(first_array)

[ 1  2  3  4  5  6  1  2 32  5  7  8]


In [4]:
twoD_array  = np.array([[1,2,3,4,5],[6,1,2,32,5,7,8]])
print(twoD_array)

[list([1, 2, 3, 4, 5]) list([6, 1, 2, 32, 5, 7, 8])]


<ipython-input-4-434636d66948>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  twoD_array  = np.array([[1,2,3,4,5],[6,1,2,32,5,7,8]])


In [5]:
empty_array = np.empty(6)
print(empty_array)

[0. 0. 0. 0. 0. 0.]


In [6]:
range_array = np.arange(4,40,3)
print(range_array)

[ 4  7 10 13 16 19 22 25 28 31 34 37]


There is a memory problem with slicing an array, to create independent slices you'd have to use the .copy() method

In [12]:
slice_array = range_array[3:-2]
print(slice_array)
slice_array[:]=0
print(slice_array)
print(range_array)

[13 16 19 22 25 28 31]
[0 0 0 0 0 0 0]
[ 4  7 10  0  0  0  0  0  0  0 34 37]


In [13]:
print(range_array)
copy_array = range_array[3:-2].copy()
copy_array[:] = 5
print(copy_array)
print(range_array)



[ 4  7 10  0  0  0  0  0  0  0 34 37]
[5 5 5 5 5 5 5]
[ 4  7 10  0  0  0  0  0  0  0 34 37]


## Transpose an array

In [16]:
five_by_ten = np.arange(0,50)
print(five_by_ten)
five_by_ten = five_by_ten.reshape(5,10)
print(five_by_ten)
print(five_by_ten.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


### Challenge to return minimum and maximum values of mini arrays in an array

In [21]:
def getMinMax(arr):
    
    res = []
    # Write code here!
    for arrx in arr:
        res.append(arrx.min())
        res.append(arrx.max())

    return res

arr = np.array([
[-3, 0, 5, -6],
[7, 2, -1, 9],
[12, -4, 3, 1],
])

getMinMax(arr)

[-6, 5, -1, 9, -4, 12]